### ISSUE TITLE
Setup gradle to distribute the different libraries (jvm, android, etc..)

### ISSUE THREAD

**Issue by joselufo** [mobilejazz/harmony-kotlin#11]

**Comment by franmontiel** [comment]
Merge kt-multiplatform-jvm into kotlin-multiplatform
Create GiHub flow to automatize publication on bintray

**Comment by franmontiel** [comment]
UPDATE:
- Tested bintray with my own account.
- Pending to create harmony@mobilejazz.com bintray account and remove credentials from build.gradle.
- Pending to use GitHub Actions to automatically upload maven artifacts to bintray

**Comment by franmontiel** [comment]
UPDATE:

- Created Bintray organization and a repo in there.
- Added documentation to do a release on the [wiki](https://sites.google.com/mobilejazz.com/wiki/harmony/multiplatform-release)
 - Changes on project on branch feature/multiplatform-release

**Comment by joselufo** [comment]
Already done in #54
