### ISSUE TITLE
Clean generic network queries 

### ISSUE THREAD

**Issue by RubenVot** [mobilejazz/harmony-kotlin#28]
In the file [GenericNetworkQuery](https://github.com/mobilejazz/harmony-kotlin/blob/kotlin-multiplatform-master/common/src/commonMain/kotlin/com.harmony.kotlin/data/datasource/network/GenericNetworkQuery.kt) there are a few queries at the beginning (the ones implemementing OAuthClientQuery) that are irrelevant at the moment. 

They have been maintained to provide compatibility to old projects but their features are probably repeated from the generic queries. 

My proposal is to just delete them and the projects that are unable to refactor at the moment can always copy the queries to their modules. 

A softer approach would be to annotate with '@deprecated' but as their features are replicated below and we are a small team I don't see a real reason to keep them there. The cleaner the better.

**Comment by franmontiel** [comment]
We can delete them or remove the "OAuth" part to make them more generic and equivalent to our generic [Queries](https://github.com/mobilejazz/harmony-kotlin/blob/kotlin-multiplatform-master/common/src/commonMain/kotlin/com.harmony.kotlin/data/query/Query.kt)

**Comment by joselufo** [comment]
I need to fully understand what's the new `GenericNetworkQuery` and also remember the `OAuth` queries that I created in the past.

I'll take a look early next week.

**Comment by jfilowk** [comment]
I like your approach, Ruben. Move to the project the old ones, mark them as deprecated there, and changed them when possible.

**Comment by joselufo** [comment]
I prefer to just apply the changes in harmony and refactor the old projects because it's only one and it's not going to be too much time. 

I spoke with @franmontiel yesterday and he will take care of this using the `GenericNetworkQuery` as I do not have time to review the projects using it and to give a good opinion. 

**Note:** When we do the refactor, please rename the `GenericNetworkQuery` to `NetworkQuery`, I do not like the Generic prefix. 

I'll review the PR when we do the refactor.

**Comment by franmontiel** [comment]
So summarizing, we all agree on:

- Moving all of the nodes inheriting from OAuthClientQuery to to the project were it is used 
- Completely remove them from harmony.
- Rename GenericNetworkQuery to NetworkQuery

@RubenVot will you take care of it?

**Comment by franmontiel** [comment]
This is already solved since the[ last update of the generic network](#35 ). Closing it.
