### ISSUE TITLE
Create a Set of Exceptions.

### ISSUE THREAD

**Issue by jfilowk** [mobilejazz/harmony-kotlin#65]
As we talk, let's try to have a set of possible exception using a Sealed class or inner classes.
We can know which are the possible exceptions options (coding and evaluating too).

_Originally posted by @jfilowk in https://github.com/mobilejazz/harmony-kotlin/pull/64#discussion_r764723530_

**Comment by joselufo** [comment]
@jfilowk do you wanna propose a PR with the change that you want to achieve?

**Comment by jfilowk** [comment]
We can close this task as we got the new exception set.
