### ISSUE TITLE
Deploy action not working

### ISSUE THREAD

**Issue by franmontiel** [mobilejazz/harmony-kotlin#68]
After migration to kotlin-dsl the [deploy](https://github.com/mobilejazz/harmony-kotlin/actions/workflows/release.yml) action stopped working (publishing on local machine works without problems).

**Comment by joselufo** [comment]
It was a temporal sonatype issue, I published a new version to sonatype and everything was fine. 

https://github.com/mobilejazz/harmony-kotlin/actions/runs/1626898131
